language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: osx
      osx_image: xcode11.3
      compiler: clang

script:
  - mkdir -p build/release
  - cd build/release
  - cmake -DBUILD_TESTS=ON -DUSE_SGTELIB=OFF -DTEST_OPENMP=OFF
  - make -j 4
  - cd ../..
  - cmake --install build/release
