language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: osx
      osx_image: xcode11.3
      compiler: clang

script:
  - mkdir -p build/release
  - cmake -DBUILD_TESTS=ON -S . -B build/release
  - cmake --build build/release --parallel 4
  - cmake --install build/release

