language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: osx
      osx_image: xcode11.3
      compiler: clang

script:
  - cmake -DBUILD_TESTS=ON -DUSE_SGTELIB=OFF -DTEST_OPENMP=OFF -S . -B build/debug -D CMAKE_BUILD_TYPE=Debug
  - cmake --build build/debug --parallel 4
  - cmake --install build/debug
